// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tui_test

import (
	"context"
	"sync"

	"github.com/TheOneWithTheWrench/skill-selector/internal/app"
	"github.com/TheOneWithTheWrench/skill-selector/internal/catalog"
	"github.com/TheOneWithTheWrench/skill-selector/internal/profile"
	"github.com/TheOneWithTheWrench/skill-selector/internal/skill_identity"
	"github.com/TheOneWithTheWrench/skill-selector/internal/source"
	skillsync "github.com/TheOneWithTheWrench/skill-selector/internal/sync"
	"github.com/TheOneWithTheWrench/skill-selector/internal/tui"
)

// Ensure, that ApplicationMock does implement tui.Application.
// If this is not the case, regenerate this file with moq.
var _ tui.Application = &ApplicationMock{}

// ApplicationMock is a mock implementation of tui.Application.
//
//	func TestSomethingThatUsesApplication(t *testing.T) {
//
//		// make and configure a mocked tui.Application
//		mockedApplication := &ApplicationMock{
//			ActivateProfileFunc: func(s string) (app.ActivateProfileResult, error) {
//				panic("mock out the ActivateProfile method")
//			},
//			AddSourceFunc: func(s string) (source.Sources, source.Source, error) {
//				panic("mock out the AddSource method")
//			},
//			CreateProfileFunc: func(s string) (profile.Profiles, error) {
//				panic("mock out the CreateProfile method")
//			},
//			ListCatalogFunc: func() (catalog.Catalog, error) {
//				panic("mock out the ListCatalog method")
//			},
//			ListProfilesFunc: func() (profile.Profiles, error) {
//				panic("mock out the ListProfiles method")
//			},
//			ListSourcesFunc: func() (source.Sources, error) {
//				panic("mock out the ListSources method")
//			},
//			ListSyncManifestsFunc: func() ([]skillsync.Manifest, error) {
//				panic("mock out the ListSyncManifests method")
//			},
//			RefreshCatalogFunc: func(contextMoqParam context.Context) (app.RefreshCatalogResult, error) {
//				panic("mock out the RefreshCatalog method")
//			},
//			RemoveProfileFunc: func(s string) (profile.Profiles, error) {
//				panic("mock out the RemoveProfile method")
//			},
//			RemoveSourceFunc: func(s string) (source.Sources, source.Source, error) {
//				panic("mock out the RemoveSource method")
//			},
//			RenameProfileFunc: func(s1 string, s2 string) (profile.Profiles, error) {
//				panic("mock out the RenameProfile method")
//			},
//			SaveActiveProfileSelectionFunc: func(identities skill_identity.Identities) (profile.Profiles, error) {
//				panic("mock out the SaveActiveProfileSelection method")
//			},
//			SwitchProfileFunc: func(s string) (profile.Profiles, error) {
//				panic("mock out the SwitchProfile method")
//			},
//			SyncSkillIdentitiesFunc: func(identities skill_identity.Identities) (skillsync.Result, error) {
//				panic("mock out the SyncSkillIdentities method")
//			},
//		}
//
//		// use mockedApplication in code that requires tui.Application
//		// and then make assertions.
//
//	}
type ApplicationMock struct {
	// ActivateProfileFunc mocks the ActivateProfile method.
	ActivateProfileFunc func(s string) (app.ActivateProfileResult, error)

	// AddSourceFunc mocks the AddSource method.
	AddSourceFunc func(s string) (source.Sources, source.Source, error)

	// CreateProfileFunc mocks the CreateProfile method.
	CreateProfileFunc func(s string) (profile.Profiles, error)

	// ListCatalogFunc mocks the ListCatalog method.
	ListCatalogFunc func() (catalog.Catalog, error)

	// ListProfilesFunc mocks the ListProfiles method.
	ListProfilesFunc func() (profile.Profiles, error)

	// ListSourcesFunc mocks the ListSources method.
	ListSourcesFunc func() (source.Sources, error)

	// ListSyncManifestsFunc mocks the ListSyncManifests method.
	ListSyncManifestsFunc func() ([]skillsync.Manifest, error)

	// RefreshCatalogFunc mocks the RefreshCatalog method.
	RefreshCatalogFunc func(contextMoqParam context.Context) (app.RefreshCatalogResult, error)

	// RemoveProfileFunc mocks the RemoveProfile method.
	RemoveProfileFunc func(s string) (profile.Profiles, error)

	// RemoveSourceFunc mocks the RemoveSource method.
	RemoveSourceFunc func(s string) (source.Sources, source.Source, error)

	// RenameProfileFunc mocks the RenameProfile method.
	RenameProfileFunc func(s1 string, s2 string) (profile.Profiles, error)

	// SaveActiveProfileSelectionFunc mocks the SaveActiveProfileSelection method.
	SaveActiveProfileSelectionFunc func(identities skill_identity.Identities) (profile.Profiles, error)

	// SwitchProfileFunc mocks the SwitchProfile method.
	SwitchProfileFunc func(s string) (profile.Profiles, error)

	// SyncSkillIdentitiesFunc mocks the SyncSkillIdentities method.
	SyncSkillIdentitiesFunc func(identities skill_identity.Identities) (skillsync.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// ActivateProfile holds details about calls to the ActivateProfile method.
		ActivateProfile []struct {
			// S is the s argument value.
			S string
		}
		// AddSource holds details about calls to the AddSource method.
		AddSource []struct {
			// S is the s argument value.
			S string
		}
		// CreateProfile holds details about calls to the CreateProfile method.
		CreateProfile []struct {
			// S is the s argument value.
			S string
		}
		// ListCatalog holds details about calls to the ListCatalog method.
		ListCatalog []struct {
		}
		// ListProfiles holds details about calls to the ListProfiles method.
		ListProfiles []struct {
		}
		// ListSources holds details about calls to the ListSources method.
		ListSources []struct {
		}
		// ListSyncManifests holds details about calls to the ListSyncManifests method.
		ListSyncManifests []struct {
		}
		// RefreshCatalog holds details about calls to the RefreshCatalog method.
		RefreshCatalog []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// RemoveProfile holds details about calls to the RemoveProfile method.
		RemoveProfile []struct {
			// S is the s argument value.
			S string
		}
		// RemoveSource holds details about calls to the RemoveSource method.
		RemoveSource []struct {
			// S is the s argument value.
			S string
		}
		// RenameProfile holds details about calls to the RenameProfile method.
		RenameProfile []struct {
			// S1 is the s1 argument value.
			S1 string
			// S2 is the s2 argument value.
			S2 string
		}
		// SaveActiveProfileSelection holds details about calls to the SaveActiveProfileSelection method.
		SaveActiveProfileSelection []struct {
			// Identities is the identities argument value.
			Identities skill_identity.Identities
		}
		// SwitchProfile holds details about calls to the SwitchProfile method.
		SwitchProfile []struct {
			// S is the s argument value.
			S string
		}
		// SyncSkillIdentities holds details about calls to the SyncSkillIdentities method.
		SyncSkillIdentities []struct {
			// Identities is the identities argument value.
			Identities skill_identity.Identities
		}
	}
	lockActivateProfile            sync.RWMutex
	lockAddSource                  sync.RWMutex
	lockCreateProfile              sync.RWMutex
	lockListCatalog                sync.RWMutex
	lockListProfiles               sync.RWMutex
	lockListSources                sync.RWMutex
	lockListSyncManifests          sync.RWMutex
	lockRefreshCatalog             sync.RWMutex
	lockRemoveProfile              sync.RWMutex
	lockRemoveSource               sync.RWMutex
	lockRenameProfile              sync.RWMutex
	lockSaveActiveProfileSelection sync.RWMutex
	lockSwitchProfile              sync.RWMutex
	lockSyncSkillIdentities        sync.RWMutex
}

// ActivateProfile calls ActivateProfileFunc.
func (mock *ApplicationMock) ActivateProfile(s string) (app.ActivateProfileResult, error) {
	if mock.ActivateProfileFunc == nil {
		panic("ApplicationMock.ActivateProfileFunc: method is nil but Application.ActivateProfile was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockActivateProfile.Lock()
	mock.calls.ActivateProfile = append(mock.calls.ActivateProfile, callInfo)
	mock.lockActivateProfile.Unlock()
	return mock.ActivateProfileFunc(s)
}

// ActivateProfileCalls gets all the calls that were made to ActivateProfile.
// Check the length with:
//
//	len(mockedApplication.ActivateProfileCalls())
func (mock *ApplicationMock) ActivateProfileCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockActivateProfile.RLock()
	calls = mock.calls.ActivateProfile
	mock.lockActivateProfile.RUnlock()
	return calls
}

// AddSource calls AddSourceFunc.
func (mock *ApplicationMock) AddSource(s string) (source.Sources, source.Source, error) {
	if mock.AddSourceFunc == nil {
		panic("ApplicationMock.AddSourceFunc: method is nil but Application.AddSource was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockAddSource.Lock()
	mock.calls.AddSource = append(mock.calls.AddSource, callInfo)
	mock.lockAddSource.Unlock()
	return mock.AddSourceFunc(s)
}

// AddSourceCalls gets all the calls that were made to AddSource.
// Check the length with:
//
//	len(mockedApplication.AddSourceCalls())
func (mock *ApplicationMock) AddSourceCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockAddSource.RLock()
	calls = mock.calls.AddSource
	mock.lockAddSource.RUnlock()
	return calls
}

// CreateProfile calls CreateProfileFunc.
func (mock *ApplicationMock) CreateProfile(s string) (profile.Profiles, error) {
	if mock.CreateProfileFunc == nil {
		panic("ApplicationMock.CreateProfileFunc: method is nil but Application.CreateProfile was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockCreateProfile.Lock()
	mock.calls.CreateProfile = append(mock.calls.CreateProfile, callInfo)
	mock.lockCreateProfile.Unlock()
	return mock.CreateProfileFunc(s)
}

// CreateProfileCalls gets all the calls that were made to CreateProfile.
// Check the length with:
//
//	len(mockedApplication.CreateProfileCalls())
func (mock *ApplicationMock) CreateProfileCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockCreateProfile.RLock()
	calls = mock.calls.CreateProfile
	mock.lockCreateProfile.RUnlock()
	return calls
}

// ListCatalog calls ListCatalogFunc.
func (mock *ApplicationMock) ListCatalog() (catalog.Catalog, error) {
	if mock.ListCatalogFunc == nil {
		panic("ApplicationMock.ListCatalogFunc: method is nil but Application.ListCatalog was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListCatalog.Lock()
	mock.calls.ListCatalog = append(mock.calls.ListCatalog, callInfo)
	mock.lockListCatalog.Unlock()
	return mock.ListCatalogFunc()
}

// ListCatalogCalls gets all the calls that were made to ListCatalog.
// Check the length with:
//
//	len(mockedApplication.ListCatalogCalls())
func (mock *ApplicationMock) ListCatalogCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListCatalog.RLock()
	calls = mock.calls.ListCatalog
	mock.lockListCatalog.RUnlock()
	return calls
}

// ListProfiles calls ListProfilesFunc.
func (mock *ApplicationMock) ListProfiles() (profile.Profiles, error) {
	if mock.ListProfilesFunc == nil {
		panic("ApplicationMock.ListProfilesFunc: method is nil but Application.ListProfiles was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListProfiles.Lock()
	mock.calls.ListProfiles = append(mock.calls.ListProfiles, callInfo)
	mock.lockListProfiles.Unlock()
	return mock.ListProfilesFunc()
}

// ListProfilesCalls gets all the calls that were made to ListProfiles.
// Check the length with:
//
//	len(mockedApplication.ListProfilesCalls())
func (mock *ApplicationMock) ListProfilesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListProfiles.RLock()
	calls = mock.calls.ListProfiles
	mock.lockListProfiles.RUnlock()
	return calls
}

// ListSources calls ListSourcesFunc.
func (mock *ApplicationMock) ListSources() (source.Sources, error) {
	if mock.ListSourcesFunc == nil {
		panic("ApplicationMock.ListSourcesFunc: method is nil but Application.ListSources was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListSources.Lock()
	mock.calls.ListSources = append(mock.calls.ListSources, callInfo)
	mock.lockListSources.Unlock()
	return mock.ListSourcesFunc()
}

// ListSourcesCalls gets all the calls that were made to ListSources.
// Check the length with:
//
//	len(mockedApplication.ListSourcesCalls())
func (mock *ApplicationMock) ListSourcesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListSources.RLock()
	calls = mock.calls.ListSources
	mock.lockListSources.RUnlock()
	return calls
}

// ListSyncManifests calls ListSyncManifestsFunc.
func (mock *ApplicationMock) ListSyncManifests() ([]skillsync.Manifest, error) {
	if mock.ListSyncManifestsFunc == nil {
		panic("ApplicationMock.ListSyncManifestsFunc: method is nil but Application.ListSyncManifests was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListSyncManifests.Lock()
	mock.calls.ListSyncManifests = append(mock.calls.ListSyncManifests, callInfo)
	mock.lockListSyncManifests.Unlock()
	return mock.ListSyncManifestsFunc()
}

// ListSyncManifestsCalls gets all the calls that were made to ListSyncManifests.
// Check the length with:
//
//	len(mockedApplication.ListSyncManifestsCalls())
func (mock *ApplicationMock) ListSyncManifestsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListSyncManifests.RLock()
	calls = mock.calls.ListSyncManifests
	mock.lockListSyncManifests.RUnlock()
	return calls
}

// RefreshCatalog calls RefreshCatalogFunc.
func (mock *ApplicationMock) RefreshCatalog(contextMoqParam context.Context) (app.RefreshCatalogResult, error) {
	if mock.RefreshCatalogFunc == nil {
		panic("ApplicationMock.RefreshCatalogFunc: method is nil but Application.RefreshCatalog was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockRefreshCatalog.Lock()
	mock.calls.RefreshCatalog = append(mock.calls.RefreshCatalog, callInfo)
	mock.lockRefreshCatalog.Unlock()
	return mock.RefreshCatalogFunc(contextMoqParam)
}

// RefreshCatalogCalls gets all the calls that were made to RefreshCatalog.
// Check the length with:
//
//	len(mockedApplication.RefreshCatalogCalls())
func (mock *ApplicationMock) RefreshCatalogCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockRefreshCatalog.RLock()
	calls = mock.calls.RefreshCatalog
	mock.lockRefreshCatalog.RUnlock()
	return calls
}

// RemoveProfile calls RemoveProfileFunc.
func (mock *ApplicationMock) RemoveProfile(s string) (profile.Profiles, error) {
	if mock.RemoveProfileFunc == nil {
		panic("ApplicationMock.RemoveProfileFunc: method is nil but Application.RemoveProfile was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockRemoveProfile.Lock()
	mock.calls.RemoveProfile = append(mock.calls.RemoveProfile, callInfo)
	mock.lockRemoveProfile.Unlock()
	return mock.RemoveProfileFunc(s)
}

// RemoveProfileCalls gets all the calls that were made to RemoveProfile.
// Check the length with:
//
//	len(mockedApplication.RemoveProfileCalls())
func (mock *ApplicationMock) RemoveProfileCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockRemoveProfile.RLock()
	calls = mock.calls.RemoveProfile
	mock.lockRemoveProfile.RUnlock()
	return calls
}

// RemoveSource calls RemoveSourceFunc.
func (mock *ApplicationMock) RemoveSource(s string) (source.Sources, source.Source, error) {
	if mock.RemoveSourceFunc == nil {
		panic("ApplicationMock.RemoveSourceFunc: method is nil but Application.RemoveSource was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockRemoveSource.Lock()
	mock.calls.RemoveSource = append(mock.calls.RemoveSource, callInfo)
	mock.lockRemoveSource.Unlock()
	return mock.RemoveSourceFunc(s)
}

// RemoveSourceCalls gets all the calls that were made to RemoveSource.
// Check the length with:
//
//	len(mockedApplication.RemoveSourceCalls())
func (mock *ApplicationMock) RemoveSourceCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockRemoveSource.RLock()
	calls = mock.calls.RemoveSource
	mock.lockRemoveSource.RUnlock()
	return calls
}

// RenameProfile calls RenameProfileFunc.
func (mock *ApplicationMock) RenameProfile(s1 string, s2 string) (profile.Profiles, error) {
	if mock.RenameProfileFunc == nil {
		panic("ApplicationMock.RenameProfileFunc: method is nil but Application.RenameProfile was just called")
	}
	callInfo := struct {
		S1 string
		S2 string
	}{
		S1: s1,
		S2: s2,
	}
	mock.lockRenameProfile.Lock()
	mock.calls.RenameProfile = append(mock.calls.RenameProfile, callInfo)
	mock.lockRenameProfile.Unlock()
	return mock.RenameProfileFunc(s1, s2)
}

// RenameProfileCalls gets all the calls that were made to RenameProfile.
// Check the length with:
//
//	len(mockedApplication.RenameProfileCalls())
func (mock *ApplicationMock) RenameProfileCalls() []struct {
	S1 string
	S2 string
} {
	var calls []struct {
		S1 string
		S2 string
	}
	mock.lockRenameProfile.RLock()
	calls = mock.calls.RenameProfile
	mock.lockRenameProfile.RUnlock()
	return calls
}

// SaveActiveProfileSelection calls SaveActiveProfileSelectionFunc.
func (mock *ApplicationMock) SaveActiveProfileSelection(identities skill_identity.Identities) (profile.Profiles, error) {
	if mock.SaveActiveProfileSelectionFunc == nil {
		panic("ApplicationMock.SaveActiveProfileSelectionFunc: method is nil but Application.SaveActiveProfileSelection was just called")
	}
	callInfo := struct {
		Identities skill_identity.Identities
	}{
		Identities: identities,
	}
	mock.lockSaveActiveProfileSelection.Lock()
	mock.calls.SaveActiveProfileSelection = append(mock.calls.SaveActiveProfileSelection, callInfo)
	mock.lockSaveActiveProfileSelection.Unlock()
	return mock.SaveActiveProfileSelectionFunc(identities)
}

// SaveActiveProfileSelectionCalls gets all the calls that were made to SaveActiveProfileSelection.
// Check the length with:
//
//	len(mockedApplication.SaveActiveProfileSelectionCalls())
func (mock *ApplicationMock) SaveActiveProfileSelectionCalls() []struct {
	Identities skill_identity.Identities
} {
	var calls []struct {
		Identities skill_identity.Identities
	}
	mock.lockSaveActiveProfileSelection.RLock()
	calls = mock.calls.SaveActiveProfileSelection
	mock.lockSaveActiveProfileSelection.RUnlock()
	return calls
}

// SwitchProfile calls SwitchProfileFunc.
func (mock *ApplicationMock) SwitchProfile(s string) (profile.Profiles, error) {
	if mock.SwitchProfileFunc == nil {
		panic("ApplicationMock.SwitchProfileFunc: method is nil but Application.SwitchProfile was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockSwitchProfile.Lock()
	mock.calls.SwitchProfile = append(mock.calls.SwitchProfile, callInfo)
	mock.lockSwitchProfile.Unlock()
	return mock.SwitchProfileFunc(s)
}

// SwitchProfileCalls gets all the calls that were made to SwitchProfile.
// Check the length with:
//
//	len(mockedApplication.SwitchProfileCalls())
func (mock *ApplicationMock) SwitchProfileCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockSwitchProfile.RLock()
	calls = mock.calls.SwitchProfile
	mock.lockSwitchProfile.RUnlock()
	return calls
}

// SyncSkillIdentities calls SyncSkillIdentitiesFunc.
func (mock *ApplicationMock) SyncSkillIdentities(identities skill_identity.Identities) (skillsync.Result, error) {
	if mock.SyncSkillIdentitiesFunc == nil {
		panic("ApplicationMock.SyncSkillIdentitiesFunc: method is nil but Application.SyncSkillIdentities was just called")
	}
	callInfo := struct {
		Identities skill_identity.Identities
	}{
		Identities: identities,
	}
	mock.lockSyncSkillIdentities.Lock()
	mock.calls.SyncSkillIdentities = append(mock.calls.SyncSkillIdentities, callInfo)
	mock.lockSyncSkillIdentities.Unlock()
	return mock.SyncSkillIdentitiesFunc(identities)
}

// SyncSkillIdentitiesCalls gets all the calls that were made to SyncSkillIdentities.
// Check the length with:
//
//	len(mockedApplication.SyncSkillIdentitiesCalls())
func (mock *ApplicationMock) SyncSkillIdentitiesCalls() []struct {
	Identities skill_identity.Identities
} {
	var calls []struct {
		Identities skill_identity.Identities
	}
	mock.lockSyncSkillIdentities.RLock()
	calls = mock.calls.SyncSkillIdentities
	mock.lockSyncSkillIdentities.RUnlock()
	return calls
}

// Ensure, that WorkflowMock does implement tui.Workflow.
// If this is not the case, regenerate this file with moq.
var _ tui.Workflow = &WorkflowMock{}

// WorkflowMock is a mock implementation of tui.Workflow.
//
//	func TestSomethingThatUsesWorkflow(t *testing.T) {
//
//		// make and configure a mocked tui.Workflow
//		mockedWorkflow := &WorkflowMock{
//			AddSourceFunc: func(contextMoqParam context.Context, s string) (tui.SourceActionResult, error) {
//				panic("mock out the AddSource method")
//			},
//			CreateProfileFunc: func(contextMoqParam context.Context, s string) (tui.ProfilesActionResult, error) {
//				panic("mock out the CreateProfile method")
//			},
//			RefreshFunc: func(contextMoqParam context.Context) (tui.RefreshActionResult, error) {
//				panic("mock out the Refresh method")
//			},
//			RemoveProfileFunc: func(contextMoqParam context.Context, s string) (tui.ProfilesActionResult, error) {
//				panic("mock out the RemoveProfile method")
//			},
//			RemoveSourceFunc: func(contextMoqParam context.Context, s string) (tui.SourceActionResult, error) {
//				panic("mock out the RemoveSource method")
//			},
//			RenameProfileFunc: func(contextMoqParam context.Context, s1 string, s2 string) (tui.ProfilesActionResult, error) {
//				panic("mock out the RenameProfile method")
//			},
//			SwitchProfileFunc: func(contextMoqParam context.Context, s string) (tui.ProfilesActionResult, error) {
//				panic("mock out the SwitchProfile method")
//			},
//			SyncFunc: func(contextMoqParam context.Context, identities skill_identity.Identities) (tui.SyncActionResult, error) {
//				panic("mock out the Sync method")
//			},
//		}
//
//		// use mockedWorkflow in code that requires tui.Workflow
//		// and then make assertions.
//
//	}
type WorkflowMock struct {
	// AddSourceFunc mocks the AddSource method.
	AddSourceFunc func(contextMoqParam context.Context, s string) (tui.SourceActionResult, error)

	// CreateProfileFunc mocks the CreateProfile method.
	CreateProfileFunc func(contextMoqParam context.Context, s string) (tui.ProfilesActionResult, error)

	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(contextMoqParam context.Context) (tui.RefreshActionResult, error)

	// RemoveProfileFunc mocks the RemoveProfile method.
	RemoveProfileFunc func(contextMoqParam context.Context, s string) (tui.ProfilesActionResult, error)

	// RemoveSourceFunc mocks the RemoveSource method.
	RemoveSourceFunc func(contextMoqParam context.Context, s string) (tui.SourceActionResult, error)

	// RenameProfileFunc mocks the RenameProfile method.
	RenameProfileFunc func(contextMoqParam context.Context, s1 string, s2 string) (tui.ProfilesActionResult, error)

	// SwitchProfileFunc mocks the SwitchProfile method.
	SwitchProfileFunc func(contextMoqParam context.Context, s string) (tui.ProfilesActionResult, error)

	// SyncFunc mocks the Sync method.
	SyncFunc func(contextMoqParam context.Context, identities skill_identity.Identities) (tui.SyncActionResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddSource holds details about calls to the AddSource method.
		AddSource []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// CreateProfile holds details about calls to the CreateProfile method.
		CreateProfile []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// RemoveProfile holds details about calls to the RemoveProfile method.
		RemoveProfile []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// RemoveSource holds details about calls to the RemoveSource method.
		RemoveSource []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// RenameProfile holds details about calls to the RenameProfile method.
		RenameProfile []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S1 is the s1 argument value.
			S1 string
			// S2 is the s2 argument value.
			S2 string
		}
		// SwitchProfile holds details about calls to the SwitchProfile method.
		SwitchProfile []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Identities is the identities argument value.
			Identities skill_identity.Identities
		}
	}
	lockAddSource     sync.RWMutex
	lockCreateProfile sync.RWMutex
	lockRefresh       sync.RWMutex
	lockRemoveProfile sync.RWMutex
	lockRemoveSource  sync.RWMutex
	lockRenameProfile sync.RWMutex
	lockSwitchProfile sync.RWMutex
	lockSync          sync.RWMutex
}

// AddSource calls AddSourceFunc.
func (mock *WorkflowMock) AddSource(contextMoqParam context.Context, s string) (tui.SourceActionResult, error) {
	if mock.AddSourceFunc == nil {
		panic("WorkflowMock.AddSourceFunc: method is nil but Workflow.AddSource was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockAddSource.Lock()
	mock.calls.AddSource = append(mock.calls.AddSource, callInfo)
	mock.lockAddSource.Unlock()
	return mock.AddSourceFunc(contextMoqParam, s)
}

// AddSourceCalls gets all the calls that were made to AddSource.
// Check the length with:
//
//	len(mockedWorkflow.AddSourceCalls())
func (mock *WorkflowMock) AddSourceCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockAddSource.RLock()
	calls = mock.calls.AddSource
	mock.lockAddSource.RUnlock()
	return calls
}

// CreateProfile calls CreateProfileFunc.
func (mock *WorkflowMock) CreateProfile(contextMoqParam context.Context, s string) (tui.ProfilesActionResult, error) {
	if mock.CreateProfileFunc == nil {
		panic("WorkflowMock.CreateProfileFunc: method is nil but Workflow.CreateProfile was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockCreateProfile.Lock()
	mock.calls.CreateProfile = append(mock.calls.CreateProfile, callInfo)
	mock.lockCreateProfile.Unlock()
	return mock.CreateProfileFunc(contextMoqParam, s)
}

// CreateProfileCalls gets all the calls that were made to CreateProfile.
// Check the length with:
//
//	len(mockedWorkflow.CreateProfileCalls())
func (mock *WorkflowMock) CreateProfileCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockCreateProfile.RLock()
	calls = mock.calls.CreateProfile
	mock.lockCreateProfile.RUnlock()
	return calls
}

// Refresh calls RefreshFunc.
func (mock *WorkflowMock) Refresh(contextMoqParam context.Context) (tui.RefreshActionResult, error) {
	if mock.RefreshFunc == nil {
		panic("WorkflowMock.RefreshFunc: method is nil but Workflow.Refresh was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(contextMoqParam)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedWorkflow.RefreshCalls())
func (mock *WorkflowMock) RefreshCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// RemoveProfile calls RemoveProfileFunc.
func (mock *WorkflowMock) RemoveProfile(contextMoqParam context.Context, s string) (tui.ProfilesActionResult, error) {
	if mock.RemoveProfileFunc == nil {
		panic("WorkflowMock.RemoveProfileFunc: method is nil but Workflow.RemoveProfile was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockRemoveProfile.Lock()
	mock.calls.RemoveProfile = append(mock.calls.RemoveProfile, callInfo)
	mock.lockRemoveProfile.Unlock()
	return mock.RemoveProfileFunc(contextMoqParam, s)
}

// RemoveProfileCalls gets all the calls that were made to RemoveProfile.
// Check the length with:
//
//	len(mockedWorkflow.RemoveProfileCalls())
func (mock *WorkflowMock) RemoveProfileCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockRemoveProfile.RLock()
	calls = mock.calls.RemoveProfile
	mock.lockRemoveProfile.RUnlock()
	return calls
}

// RemoveSource calls RemoveSourceFunc.
func (mock *WorkflowMock) RemoveSource(contextMoqParam context.Context, s string) (tui.SourceActionResult, error) {
	if mock.RemoveSourceFunc == nil {
		panic("WorkflowMock.RemoveSourceFunc: method is nil but Workflow.RemoveSource was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockRemoveSource.Lock()
	mock.calls.RemoveSource = append(mock.calls.RemoveSource, callInfo)
	mock.lockRemoveSource.Unlock()
	return mock.RemoveSourceFunc(contextMoqParam, s)
}

// RemoveSourceCalls gets all the calls that were made to RemoveSource.
// Check the length with:
//
//	len(mockedWorkflow.RemoveSourceCalls())
func (mock *WorkflowMock) RemoveSourceCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockRemoveSource.RLock()
	calls = mock.calls.RemoveSource
	mock.lockRemoveSource.RUnlock()
	return calls
}

// RenameProfile calls RenameProfileFunc.
func (mock *WorkflowMock) RenameProfile(contextMoqParam context.Context, s1 string, s2 string) (tui.ProfilesActionResult, error) {
	if mock.RenameProfileFunc == nil {
		panic("WorkflowMock.RenameProfileFunc: method is nil but Workflow.RenameProfile was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S1              string
		S2              string
	}{
		ContextMoqParam: contextMoqParam,
		S1:              s1,
		S2:              s2,
	}
	mock.lockRenameProfile.Lock()
	mock.calls.RenameProfile = append(mock.calls.RenameProfile, callInfo)
	mock.lockRenameProfile.Unlock()
	return mock.RenameProfileFunc(contextMoqParam, s1, s2)
}

// RenameProfileCalls gets all the calls that were made to RenameProfile.
// Check the length with:
//
//	len(mockedWorkflow.RenameProfileCalls())
func (mock *WorkflowMock) RenameProfileCalls() []struct {
	ContextMoqParam context.Context
	S1              string
	S2              string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S1              string
		S2              string
	}
	mock.lockRenameProfile.RLock()
	calls = mock.calls.RenameProfile
	mock.lockRenameProfile.RUnlock()
	return calls
}

// SwitchProfile calls SwitchProfileFunc.
func (mock *WorkflowMock) SwitchProfile(contextMoqParam context.Context, s string) (tui.ProfilesActionResult, error) {
	if mock.SwitchProfileFunc == nil {
		panic("WorkflowMock.SwitchProfileFunc: method is nil but Workflow.SwitchProfile was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockSwitchProfile.Lock()
	mock.calls.SwitchProfile = append(mock.calls.SwitchProfile, callInfo)
	mock.lockSwitchProfile.Unlock()
	return mock.SwitchProfileFunc(contextMoqParam, s)
}

// SwitchProfileCalls gets all the calls that were made to SwitchProfile.
// Check the length with:
//
//	len(mockedWorkflow.SwitchProfileCalls())
func (mock *WorkflowMock) SwitchProfileCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockSwitchProfile.RLock()
	calls = mock.calls.SwitchProfile
	mock.lockSwitchProfile.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *WorkflowMock) Sync(contextMoqParam context.Context, identities skill_identity.Identities) (tui.SyncActionResult, error) {
	if mock.SyncFunc == nil {
		panic("WorkflowMock.SyncFunc: method is nil but Workflow.Sync was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Identities      skill_identity.Identities
	}{
		ContextMoqParam: contextMoqParam,
		Identities:      identities,
	}
	mock.lockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	mock.lockSync.Unlock()
	return mock.SyncFunc(contextMoqParam, identities)
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//
//	len(mockedWorkflow.SyncCalls())
func (mock *WorkflowMock) SyncCalls() []struct {
	ContextMoqParam context.Context
	Identities      skill_identity.Identities
} {
	var calls []struct {
		ContextMoqParam context.Context
		Identities      skill_identity.Identities
	}
	mock.lockSync.RLock()
	calls = mock.calls.Sync
	mock.lockSync.RUnlock()
	return calls
}
