// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cli_test

import (
	"context"
	"sync"

	"github.com/TheOneWithTheWrench/skill-switcher-v2/internal/app"
	"github.com/TheOneWithTheWrench/skill-switcher-v2/internal/catalog"
	"github.com/TheOneWithTheWrench/skill-switcher-v2/internal/cli"
	"github.com/TheOneWithTheWrench/skill-switcher-v2/internal/skillidentity"
	"github.com/TheOneWithTheWrench/skill-switcher-v2/internal/source"
	skillsync "github.com/TheOneWithTheWrench/skill-switcher-v2/internal/sync"
)

// Ensure, that ApplicationMock does implement cli.Application.
// If this is not the case, regenerate this file with moq.
var _ cli.Application = &ApplicationMock{}

// ApplicationMock is a mock implementation of cli.Application.
//
//	func TestSomethingThatUsesApplication(t *testing.T) {
//
//		// make and configure a mocked cli.Application
//		mockedApplication := &ApplicationMock{
//			AddSourceFunc: func(s string) (source.Sources, source.Source, error) {
//				panic("mock out the AddSource method")
//			},
//			ListCatalogFunc: func() (catalog.Catalog, error) {
//				panic("mock out the ListCatalog method")
//			},
//			ListSourcesFunc: func() (source.Sources, error) {
//				panic("mock out the ListSources method")
//			},
//			ListSyncManifestsFunc: func() ([]skillsync.Manifest, error) {
//				panic("mock out the ListSyncManifests method")
//			},
//			RefreshCatalogFunc: func(contextMoqParam context.Context) (app.RefreshCatalogResult, error) {
//				panic("mock out the RefreshCatalog method")
//			},
//			RemoveSourceFunc: func(s string) (source.Sources, source.Source, error) {
//				panic("mock out the RemoveSource method")
//			},
//			SyncSkillIdentitiesFunc: func(identities skillidentity.Identities) (skillsync.Result, error) {
//				panic("mock out the SyncSkillIdentities method")
//			},
//		}
//
//		// use mockedApplication in code that requires cli.Application
//		// and then make assertions.
//
//	}
type ApplicationMock struct {
	// AddSourceFunc mocks the AddSource method.
	AddSourceFunc func(s string) (source.Sources, source.Source, error)

	// ListCatalogFunc mocks the ListCatalog method.
	ListCatalogFunc func() (catalog.Catalog, error)

	// ListSourcesFunc mocks the ListSources method.
	ListSourcesFunc func() (source.Sources, error)

	// ListSyncManifestsFunc mocks the ListSyncManifests method.
	ListSyncManifestsFunc func() ([]skillsync.Manifest, error)

	// RefreshCatalogFunc mocks the RefreshCatalog method.
	RefreshCatalogFunc func(contextMoqParam context.Context) (app.RefreshCatalogResult, error)

	// RemoveSourceFunc mocks the RemoveSource method.
	RemoveSourceFunc func(s string) (source.Sources, source.Source, error)

	// SyncSkillIdentitiesFunc mocks the SyncSkillIdentities method.
	SyncSkillIdentitiesFunc func(identities skillidentity.Identities) (skillsync.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddSource holds details about calls to the AddSource method.
		AddSource []struct {
			// S is the s argument value.
			S string
		}
		// ListCatalog holds details about calls to the ListCatalog method.
		ListCatalog []struct {
		}
		// ListSources holds details about calls to the ListSources method.
		ListSources []struct {
		}
		// ListSyncManifests holds details about calls to the ListSyncManifests method.
		ListSyncManifests []struct {
		}
		// RefreshCatalog holds details about calls to the RefreshCatalog method.
		RefreshCatalog []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// RemoveSource holds details about calls to the RemoveSource method.
		RemoveSource []struct {
			// S is the s argument value.
			S string
		}
		// SyncSkillIdentities holds details about calls to the SyncSkillIdentities method.
		SyncSkillIdentities []struct {
			// Identities is the identities argument value.
			Identities skillidentity.Identities
		}
	}
	lockAddSource           sync.RWMutex
	lockListCatalog         sync.RWMutex
	lockListSources         sync.RWMutex
	lockListSyncManifests   sync.RWMutex
	lockRefreshCatalog      sync.RWMutex
	lockRemoveSource        sync.RWMutex
	lockSyncSkillIdentities sync.RWMutex
}

// AddSource calls AddSourceFunc.
func (mock *ApplicationMock) AddSource(s string) (source.Sources, source.Source, error) {
	if mock.AddSourceFunc == nil {
		panic("ApplicationMock.AddSourceFunc: method is nil but Application.AddSource was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockAddSource.Lock()
	mock.calls.AddSource = append(mock.calls.AddSource, callInfo)
	mock.lockAddSource.Unlock()
	return mock.AddSourceFunc(s)
}

// AddSourceCalls gets all the calls that were made to AddSource.
// Check the length with:
//
//	len(mockedApplication.AddSourceCalls())
func (mock *ApplicationMock) AddSourceCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockAddSource.RLock()
	calls = mock.calls.AddSource
	mock.lockAddSource.RUnlock()
	return calls
}

// ListCatalog calls ListCatalogFunc.
func (mock *ApplicationMock) ListCatalog() (catalog.Catalog, error) {
	if mock.ListCatalogFunc == nil {
		panic("ApplicationMock.ListCatalogFunc: method is nil but Application.ListCatalog was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListCatalog.Lock()
	mock.calls.ListCatalog = append(mock.calls.ListCatalog, callInfo)
	mock.lockListCatalog.Unlock()
	return mock.ListCatalogFunc()
}

// ListCatalogCalls gets all the calls that were made to ListCatalog.
// Check the length with:
//
//	len(mockedApplication.ListCatalogCalls())
func (mock *ApplicationMock) ListCatalogCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListCatalog.RLock()
	calls = mock.calls.ListCatalog
	mock.lockListCatalog.RUnlock()
	return calls
}

// ListSources calls ListSourcesFunc.
func (mock *ApplicationMock) ListSources() (source.Sources, error) {
	if mock.ListSourcesFunc == nil {
		panic("ApplicationMock.ListSourcesFunc: method is nil but Application.ListSources was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListSources.Lock()
	mock.calls.ListSources = append(mock.calls.ListSources, callInfo)
	mock.lockListSources.Unlock()
	return mock.ListSourcesFunc()
}

// ListSourcesCalls gets all the calls that were made to ListSources.
// Check the length with:
//
//	len(mockedApplication.ListSourcesCalls())
func (mock *ApplicationMock) ListSourcesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListSources.RLock()
	calls = mock.calls.ListSources
	mock.lockListSources.RUnlock()
	return calls
}

// ListSyncManifests calls ListSyncManifestsFunc.
func (mock *ApplicationMock) ListSyncManifests() ([]skillsync.Manifest, error) {
	if mock.ListSyncManifestsFunc == nil {
		panic("ApplicationMock.ListSyncManifestsFunc: method is nil but Application.ListSyncManifests was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListSyncManifests.Lock()
	mock.calls.ListSyncManifests = append(mock.calls.ListSyncManifests, callInfo)
	mock.lockListSyncManifests.Unlock()
	return mock.ListSyncManifestsFunc()
}

// ListSyncManifestsCalls gets all the calls that were made to ListSyncManifests.
// Check the length with:
//
//	len(mockedApplication.ListSyncManifestsCalls())
func (mock *ApplicationMock) ListSyncManifestsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListSyncManifests.RLock()
	calls = mock.calls.ListSyncManifests
	mock.lockListSyncManifests.RUnlock()
	return calls
}

// RefreshCatalog calls RefreshCatalogFunc.
func (mock *ApplicationMock) RefreshCatalog(contextMoqParam context.Context) (app.RefreshCatalogResult, error) {
	if mock.RefreshCatalogFunc == nil {
		panic("ApplicationMock.RefreshCatalogFunc: method is nil but Application.RefreshCatalog was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockRefreshCatalog.Lock()
	mock.calls.RefreshCatalog = append(mock.calls.RefreshCatalog, callInfo)
	mock.lockRefreshCatalog.Unlock()
	return mock.RefreshCatalogFunc(contextMoqParam)
}

// RefreshCatalogCalls gets all the calls that were made to RefreshCatalog.
// Check the length with:
//
//	len(mockedApplication.RefreshCatalogCalls())
func (mock *ApplicationMock) RefreshCatalogCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockRefreshCatalog.RLock()
	calls = mock.calls.RefreshCatalog
	mock.lockRefreshCatalog.RUnlock()
	return calls
}

// RemoveSource calls RemoveSourceFunc.
func (mock *ApplicationMock) RemoveSource(s string) (source.Sources, source.Source, error) {
	if mock.RemoveSourceFunc == nil {
		panic("ApplicationMock.RemoveSourceFunc: method is nil but Application.RemoveSource was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockRemoveSource.Lock()
	mock.calls.RemoveSource = append(mock.calls.RemoveSource, callInfo)
	mock.lockRemoveSource.Unlock()
	return mock.RemoveSourceFunc(s)
}

// RemoveSourceCalls gets all the calls that were made to RemoveSource.
// Check the length with:
//
//	len(mockedApplication.RemoveSourceCalls())
func (mock *ApplicationMock) RemoveSourceCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockRemoveSource.RLock()
	calls = mock.calls.RemoveSource
	mock.lockRemoveSource.RUnlock()
	return calls
}

// SyncSkillIdentities calls SyncSkillIdentitiesFunc.
func (mock *ApplicationMock) SyncSkillIdentities(identities skillidentity.Identities) (skillsync.Result, error) {
	if mock.SyncSkillIdentitiesFunc == nil {
		panic("ApplicationMock.SyncSkillIdentitiesFunc: method is nil but Application.SyncSkillIdentities was just called")
	}
	callInfo := struct {
		Identities skillidentity.Identities
	}{
		Identities: identities,
	}
	mock.lockSyncSkillIdentities.Lock()
	mock.calls.SyncSkillIdentities = append(mock.calls.SyncSkillIdentities, callInfo)
	mock.lockSyncSkillIdentities.Unlock()
	return mock.SyncSkillIdentitiesFunc(identities)
}

// SyncSkillIdentitiesCalls gets all the calls that were made to SyncSkillIdentities.
// Check the length with:
//
//	len(mockedApplication.SyncSkillIdentitiesCalls())
func (mock *ApplicationMock) SyncSkillIdentitiesCalls() []struct {
	Identities skillidentity.Identities
} {
	var calls []struct {
		Identities skillidentity.Identities
	}
	mock.lockSyncSkillIdentities.RLock()
	calls = mock.calls.SyncSkillIdentities
	mock.lockSyncSkillIdentities.RUnlock()
	return calls
}
