// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package app_test

import (
	"context"
	"sync"
	"time"

	"github.com/TheOneWithTheWrench/skill-selector/internal/app"
	"github.com/TheOneWithTheWrench/skill-selector/internal/catalog"
	"github.com/TheOneWithTheWrench/skill-selector/internal/profile"
	"github.com/TheOneWithTheWrench/skill-selector/internal/source"
	skillsync "github.com/TheOneWithTheWrench/skill-selector/internal/sync"
)

// Ensure, that ClockMock does implement app.Clock.
// If this is not the case, regenerate this file with moq.
var _ app.Clock = &ClockMock{}

// ClockMock is a mock implementation of app.Clock.
//
//	func TestSomethingThatUsesClock(t *testing.T) {
//
//		// make and configure a mocked app.Clock
//		mockedClock := &ClockMock{
//			NowFunc: func() time.Time {
//				panic("mock out the Now method")
//			},
//		}
//
//		// use mockedClock in code that requires app.Clock
//		// and then make assertions.
//
//	}
type ClockMock struct {
	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// calls tracks calls to the methods.
	calls struct {
		// Now holds details about calls to the Now method.
		Now []struct {
		}
	}
	lockNow sync.RWMutex
}

// Now calls NowFunc.
func (mock *ClockMock) Now() time.Time {
	if mock.NowFunc == nil {
		panic("ClockMock.NowFunc: method is nil but Clock.Now was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//
//	len(mockedClock.NowCalls())
func (mock *ClockMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}

// Ensure, that SourceRepositoryMock does implement app.SourceRepository.
// If this is not the case, regenerate this file with moq.
var _ app.SourceRepository = &SourceRepositoryMock{}

// SourceRepositoryMock is a mock implementation of app.SourceRepository.
//
//	func TestSomethingThatUsesSourceRepository(t *testing.T) {
//
//		// make and configure a mocked app.SourceRepository
//		mockedSourceRepository := &SourceRepositoryMock{
//			LoadFunc: func() (source.Sources, error) {
//				panic("mock out the Load method")
//			},
//			SaveFunc: func(sources source.Sources) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedSourceRepository in code that requires app.SourceRepository
//		// and then make assertions.
//
//	}
type SourceRepositoryMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func() (source.Sources, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(sources source.Sources) error

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Sources is the sources argument value.
			Sources source.Sources
		}
	}
	lockLoad sync.RWMutex
	lockSave sync.RWMutex
}

// Load calls LoadFunc.
func (mock *SourceRepositoryMock) Load() (source.Sources, error) {
	if mock.LoadFunc == nil {
		panic("SourceRepositoryMock.LoadFunc: method is nil but SourceRepository.Load was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc()
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedSourceRepository.LoadCalls())
func (mock *SourceRepositoryMock) LoadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *SourceRepositoryMock) Save(sources source.Sources) error {
	if mock.SaveFunc == nil {
		panic("SourceRepositoryMock.SaveFunc: method is nil but SourceRepository.Save was just called")
	}
	callInfo := struct {
		Sources source.Sources
	}{
		Sources: sources,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(sources)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedSourceRepository.SaveCalls())
func (mock *SourceRepositoryMock) SaveCalls() []struct {
	Sources source.Sources
} {
	var calls []struct {
		Sources source.Sources
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Ensure, that SourceRefresherMock does implement app.SourceRefresher.
// If this is not the case, regenerate this file with moq.
var _ app.SourceRefresher = &SourceRefresherMock{}

// SourceRefresherMock is a mock implementation of app.SourceRefresher.
//
//	func TestSomethingThatUsesSourceRefresher(t *testing.T) {
//
//		// make and configure a mocked app.SourceRefresher
//		mockedSourceRefresher := &SourceRefresherMock{
//			RefreshFunc: func(ctx context.Context, mirror source.Mirror) (source.RefreshResult, error) {
//				panic("mock out the Refresh method")
//			},
//		}
//
//		// use mockedSourceRefresher in code that requires app.SourceRefresher
//		// and then make assertions.
//
//	}
type SourceRefresherMock struct {
	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(ctx context.Context, mirror source.Mirror) (source.RefreshResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Mirror is the mirror argument value.
			Mirror source.Mirror
		}
	}
	lockRefresh sync.RWMutex
}

// Refresh calls RefreshFunc.
func (mock *SourceRefresherMock) Refresh(ctx context.Context, mirror source.Mirror) (source.RefreshResult, error) {
	if mock.RefreshFunc == nil {
		panic("SourceRefresherMock.RefreshFunc: method is nil but SourceRefresher.Refresh was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Mirror source.Mirror
	}{
		Ctx:    ctx,
		Mirror: mirror,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(ctx, mirror)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedSourceRefresher.RefreshCalls())
func (mock *SourceRefresherMock) RefreshCalls() []struct {
	Ctx    context.Context
	Mirror source.Mirror
} {
	var calls []struct {
		Ctx    context.Context
		Mirror source.Mirror
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// Ensure, that CatalogRepositoryMock does implement app.CatalogRepository.
// If this is not the case, regenerate this file with moq.
var _ app.CatalogRepository = &CatalogRepositoryMock{}

// CatalogRepositoryMock is a mock implementation of app.CatalogRepository.
//
//	func TestSomethingThatUsesCatalogRepository(t *testing.T) {
//
//		// make and configure a mocked app.CatalogRepository
//		mockedCatalogRepository := &CatalogRepositoryMock{
//			LoadFunc: func() (catalog.Catalog, error) {
//				panic("mock out the Load method")
//			},
//			SaveFunc: func(catalogMoqParam catalog.Catalog) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedCatalogRepository in code that requires app.CatalogRepository
//		// and then make assertions.
//
//	}
type CatalogRepositoryMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func() (catalog.Catalog, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(catalogMoqParam catalog.Catalog) error

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// CatalogMoqParam is the catalogMoqParam argument value.
			CatalogMoqParam catalog.Catalog
		}
	}
	lockLoad sync.RWMutex
	lockSave sync.RWMutex
}

// Load calls LoadFunc.
func (mock *CatalogRepositoryMock) Load() (catalog.Catalog, error) {
	if mock.LoadFunc == nil {
		panic("CatalogRepositoryMock.LoadFunc: method is nil but CatalogRepository.Load was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc()
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedCatalogRepository.LoadCalls())
func (mock *CatalogRepositoryMock) LoadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *CatalogRepositoryMock) Save(catalogMoqParam catalog.Catalog) error {
	if mock.SaveFunc == nil {
		panic("CatalogRepositoryMock.SaveFunc: method is nil but CatalogRepository.Save was just called")
	}
	callInfo := struct {
		CatalogMoqParam catalog.Catalog
	}{
		CatalogMoqParam: catalogMoqParam,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(catalogMoqParam)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedCatalogRepository.SaveCalls())
func (mock *CatalogRepositoryMock) SaveCalls() []struct {
	CatalogMoqParam catalog.Catalog
} {
	var calls []struct {
		CatalogMoqParam catalog.Catalog
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Ensure, that ProfileRepositoryMock does implement app.ProfileRepository.
// If this is not the case, regenerate this file with moq.
var _ app.ProfileRepository = &ProfileRepositoryMock{}

// ProfileRepositoryMock is a mock implementation of app.ProfileRepository.
//
//	func TestSomethingThatUsesProfileRepository(t *testing.T) {
//
//		// make and configure a mocked app.ProfileRepository
//		mockedProfileRepository := &ProfileRepositoryMock{
//			LoadFunc: func() (profile.Profiles, error) {
//				panic("mock out the Load method")
//			},
//			SaveFunc: func(profiles profile.Profiles) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedProfileRepository in code that requires app.ProfileRepository
//		// and then make assertions.
//
//	}
type ProfileRepositoryMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func() (profile.Profiles, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(profiles profile.Profiles) error

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Profiles is the profiles argument value.
			Profiles profile.Profiles
		}
	}
	lockLoad sync.RWMutex
	lockSave sync.RWMutex
}

// Load calls LoadFunc.
func (mock *ProfileRepositoryMock) Load() (profile.Profiles, error) {
	if mock.LoadFunc == nil {
		panic("ProfileRepositoryMock.LoadFunc: method is nil but ProfileRepository.Load was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc()
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedProfileRepository.LoadCalls())
func (mock *ProfileRepositoryMock) LoadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *ProfileRepositoryMock) Save(profiles profile.Profiles) error {
	if mock.SaveFunc == nil {
		panic("ProfileRepositoryMock.SaveFunc: method is nil but ProfileRepository.Save was just called")
	}
	callInfo := struct {
		Profiles profile.Profiles
	}{
		Profiles: profiles,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(profiles)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedProfileRepository.SaveCalls())
func (mock *ProfileRepositoryMock) SaveCalls() []struct {
	Profiles profile.Profiles
} {
	var calls []struct {
		Profiles profile.Profiles
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Ensure, that SyncManifestRepositoryMock does implement app.SyncManifestRepository.
// If this is not the case, regenerate this file with moq.
var _ app.SyncManifestRepository = &SyncManifestRepositoryMock{}

// SyncManifestRepositoryMock is a mock implementation of app.SyncManifestRepository.
//
//	func TestSomethingThatUsesSyncManifestRepository(t *testing.T) {
//
//		// make and configure a mocked app.SyncManifestRepository
//		mockedSyncManifestRepository := &SyncManifestRepositoryMock{
//			LoadAllFunc: func() ([]skillsync.Manifest, error) {
//				panic("mock out the LoadAll method")
//			},
//			SaveFunc: func(manifest skillsync.Manifest) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedSyncManifestRepository in code that requires app.SyncManifestRepository
//		// and then make assertions.
//
//	}
type SyncManifestRepositoryMock struct {
	// LoadAllFunc mocks the LoadAll method.
	LoadAllFunc func() ([]skillsync.Manifest, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(manifest skillsync.Manifest) error

	// calls tracks calls to the methods.
	calls struct {
		// LoadAll holds details about calls to the LoadAll method.
		LoadAll []struct {
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Manifest is the manifest argument value.
			Manifest skillsync.Manifest
		}
	}
	lockLoadAll sync.RWMutex
	lockSave    sync.RWMutex
}

// LoadAll calls LoadAllFunc.
func (mock *SyncManifestRepositoryMock) LoadAll() ([]skillsync.Manifest, error) {
	if mock.LoadAllFunc == nil {
		panic("SyncManifestRepositoryMock.LoadAllFunc: method is nil but SyncManifestRepository.LoadAll was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoadAll.Lock()
	mock.calls.LoadAll = append(mock.calls.LoadAll, callInfo)
	mock.lockLoadAll.Unlock()
	return mock.LoadAllFunc()
}

// LoadAllCalls gets all the calls that were made to LoadAll.
// Check the length with:
//
//	len(mockedSyncManifestRepository.LoadAllCalls())
func (mock *SyncManifestRepositoryMock) LoadAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoadAll.RLock()
	calls = mock.calls.LoadAll
	mock.lockLoadAll.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *SyncManifestRepositoryMock) Save(manifest skillsync.Manifest) error {
	if mock.SaveFunc == nil {
		panic("SyncManifestRepositoryMock.SaveFunc: method is nil but SyncManifestRepository.Save was just called")
	}
	callInfo := struct {
		Manifest skillsync.Manifest
	}{
		Manifest: manifest,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(manifest)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedSyncManifestRepository.SaveCalls())
func (mock *SyncManifestRepositoryMock) SaveCalls() []struct {
	Manifest skillsync.Manifest
} {
	var calls []struct {
		Manifest skillsync.Manifest
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
