// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package source_test

import (
	"context"
	"sync"

	"github.com/TheOneWithTheWrench/skill-selector/internal/source"
)

// Ensure, that RunnerMock does implement source.Runner.
// If this is not the case, regenerate this file with moq.
var _ source.Runner = &RunnerMock{}

// RunnerMock is a mock implementation of source.Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked source.Runner
//		mockedRunner := &RunnerMock{
//			RunFunc: func(ctx context.Context, workdir string, name string, args ...string) error {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedRunner in code that requires source.Runner
//		// and then make assertions.
//
//	}
type RunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, workdir string, name string, args ...string) error

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workdir is the workdir argument value.
			Workdir string
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *RunnerMock) Run(ctx context.Context, workdir string, name string, args ...string) error {
	if mock.RunFunc == nil {
		panic("RunnerMock.RunFunc: method is nil but Runner.Run was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Workdir string
		Name    string
		Args    []string
	}{
		Ctx:     ctx,
		Workdir: workdir,
		Name:    name,
		Args:    args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, workdir, name, args...)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedRunner.RunCalls())
func (mock *RunnerMock) RunCalls() []struct {
	Ctx     context.Context
	Workdir string
	Name    string
	Args    []string
} {
	var calls []struct {
		Ctx     context.Context
		Workdir string
		Name    string
		Args    []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
